
import { BOQMasterItem } from './types';

export const STORAGE_KEY = 'HC_FRAMEWORK_MANAGER_V2';

export const BOQ_MASTER: BOQMasterItem[] = [
  // SECTION A
  { "section": "A", "bill": "SECTION A", "desc": "LAYING OF PUBLIC SEWERS", "unit": "Nil", "rate": null, "rateStr": "", "kind": "section" },
  { "section": "A", "bill": "A1", "desc": "Laying of public sewers and branch sewers (from limits of private property to street sewer)", "unit": "Nil", "rate": null, "rateStr": "", "kind": "group" },
  { "section": "A", "bill": "A1.1", "desc": "Laying of uPVC gravity pipes as specified at depth less or equal to 1.5m", "unit": "Nil", "rate": null, "rateStr": "", "kind": "subsection" },
  { "section": "A", "bill": "A1.1.1", "desc": "DN 160", "unit": "m", "rate": 8430.0, "rateStr": "8,430.00", "kind": "item" },
  { "section": "A", "bill": "A1.1.2", "desc": "DN 200", "unit": "m", "rate": 9500.0, "rateStr": "9,500.00", "kind": "item" },
  
  { "section": "A", "bill": "A2", "desc": "Construction of Manholes", "unit": "Nil", "rate": null, "rateStr": "", "kind": "group" },
  { "section": "A", "bill": "A2.1", "desc": "Construction circular/rectangular R.C manhole for sewers", "unit": "Nil", "rate": null, "rateStr": "", "kind": "subsection" },
  { "section": "A", "bill": "A2.1.1", "desc": "Type A - Invert levels at depth less to 1.0m", "unit": "No", "rate": 81610.0, "rateStr": "81,610.00", "kind": "item" },
  { "section": "A", "bill": "A2.1.2", "desc": "Type A - depth above 1m and to 1.5m", "unit": "No", "rate": 109390.0, "rateStr": "109,390.00", "kind": "item" },
  { "section": "A", "bill": "A2.1.3", "desc": "Type A - depth above 1.5m to 2m", "unit": "No", "rate": 121920.0, "rateStr": "121,920.00", "kind": "item" },
  { "section": "A", "bill": "A2.1.4", "desc": "Type A - depth above 2m and to 2.5m", "unit": "No", "rate": 131260.0, "rateStr": "131,260.00", "kind": "item" },
  { "section": "A", "bill": "A2.1.5", "desc": "Type A - depth above 2.5m to 3m", "unit": "No", "rate": 165910.0, "rateStr": "165,910.00", "kind": "item" },
  { "section": "A", "bill": "A2.1.6", "desc": "Type B - depth above 3m and to 3.5m", "unit": "No", "rate": 190490.0, "rateStr": "190,490.00", "kind": "item" },
  { "section": "A", "bill": "A2.1.7", "desc": "Type B - depth above 3.5m and to 4m", "unit": "No", "rate": 215070.0, "rateStr": "215,070.00", "kind": "item" },
  { "section": "A", "bill": "A2.1.8", "desc": "Type B - depth above 4m and to 4.5m", "unit": "No", "rate": 239640.0, "rateStr": "239,640.00", "kind": "item" },
  { "section": "A", "bill": "A2.1.9", "desc": "Type B - depth above 4.5m and to 5m", "unit": "No", "rate": 264220.0, "rateStr": "264,220.00", "kind": "item" },
  
  { "section": "A", "bill": "A3", "desc": "Connection on existing structures and sewers", "unit": "Nil", "rate": null, "rateStr": "", "kind": "group" },
  { "section": "A", "bill": "A3.1", "desc": "Connection of new branch sewers DN 160/200 to existing street sewer", "unit": "No", "rate": 34370.0, "rateStr": "34,370.00", "kind": "item" },
  { "section": "A", "bill": "A3.2", "desc": "Connection of new branch sewers DN 250 to existing street sewer", "unit": "No", "rate": 36250.0, "rateStr": "36,250.00", "kind": "item" },
  { "section": "A", "bill": "A3.3", "desc": "Connection of new public and branch sewers into existing manholes", "unit": "No", "rate": 37290.0, "rateStr": "37,290.00", "kind": "item" },
  
  { "section": "A", "bill": "A4", "desc": "Extraovers", "unit": "Nil", "rate": null, "rateStr": "", "kind": "group" },
  { "section": "A", "bill": "A4.1", "desc": "Extraover prices A1.1 for laying of pipes in deeper trenches", "unit": "Nil", "rate": null, "rateStr": "", "kind": "subsection" },
  { "section": "A", "bill": "A4.1.1", "desc": "At depth above 1.5m and upto 2m", "unit": "m", "rate": 3350.0, "rateStr": "3,350.00", "kind": "item" },
  { "section": "A", "bill": "A4.1.2", "desc": "At depth above 1.5m and upto 2.5m", "unit": "m", "rate": 7520.0, "rateStr": "7,520.00", "kind": "item" },
  { "section": "A", "bill": "A4.1.3", "desc": "At depth above 1.5m and upto 3m", "unit": "m", "rate": 12770.0, "rateStr": "12,770.00", "kind": "item" },
  { "section": "A", "bill": "A4.1.4", "desc": "At depth above 1.5m and upto 3.5m", "unit": "m", "rate": 20980.0, "rateStr": "20,980.00", "kind": "item" },
  { "section": "A", "bill": "A4.1.5", "desc": "At depth above 1.5m and upto 4m", "unit": "m", "rate": 30730.0, "rateStr": "30,730.00", "kind": "item" },
  { "section": "A", "bill": "A4.1.6", "desc": "At depth above 1.5m and upto 4.5m", "unit": "m", "rate": 42420.0, "rateStr": "42,420.00", "kind": "item" },
  { "section": "A", "bill": "A4.1.7", "desc": "At depth above 1.5m and upto 5m and above", "unit": "m", "rate": 56220.0, "rateStr": "56,220.00", "kind": "item" },
  
  { "section": "A", "bill": "A4.2", "desc": "Mechanical saddle", "unit": "Nil", "rate": null, "rateStr": "", "kind": "subsection" },
  { "section": "A", "bill": "A4.2.1", "desc": "Extra over prices A3.1 for the use of a mechanical saddle", "unit": "No", "rate": 9900.0, "rateStr": "9,900.00", "kind": "item" },
  { "section": "A", "bill": "A4.2.2", "desc": "Ditto but for prices A3.2", "unit": "No", "rate": 11200.0, "rateStr": "11,200.00", "kind": "item" },

  // SECTION B
  { "section": "B", "bill": "SECTION B", "desc": "LAYING OF PROPERTY HOUSE SEWERS", "unit": "Nil", "rate": null, "rateStr": "", "kind": "section" },
  { "section": "B", "bill": "Note", "desc": "Laying of property house sewer and branch sewer (from limits of property to IC A)", "unit": "Nil", "rate": null, "rateStr": "", "kind": "note" },
  { "section": "B", "bill": "B1", "desc": "Laying of uPVC gravity pipes as specified at depth less or equal to 1.0m", "unit": "Nil", "rate": null, "rateStr": "", "kind": "group" },
  { "section": "B", "bill": "B1.1", "desc": "DN 110", "unit": "m", "rate": 3400.0, "rateStr": "3,400.00", "kind": "item" },
  { "section": "B", "bill": "B1.2", "desc": "DN 160", "unit": "m", "rate": 3780.0, "rateStr": "3,780.00", "kind": "item" },
  { "section": "B", "bill": "B1.3", "desc": "DN 200", "unit": "m", "rate": 5550.0, "rateStr": "5,550.00", "kind": "item" },
  
  { "section": "B", "bill": "B2", "desc": "Construction of Property House Inspection Chambers", "unit": "Nil", "rate": null, "rateStr": "", "kind": "group" },
  { "section": "B", "bill": "B2.1", "desc": "Construction of rectangular blockwork manhole / inspection chamber", "unit": "Nil", "rate": null, "rateStr": "", "kind": "subsection" },
  { "section": "B", "bill": "B2.1.1", "desc": "Type C - invert levels at depth less than 1.0m", "unit": "No", "rate": 17330.0, "rateStr": "17,330.00", "kind": "item" },
  { "section": "B", "bill": "B2.1.2", "desc": "Type D - depth above 1m and upto 1.5m", "unit": "No", "rate": 36270.0, "rateStr": "36,270.00", "kind": "item" },
  { "section": "B", "bill": "B2.1.3", "desc": "Type D - depth above 1.5m and upto 2m", "unit": "No", "rate": 37990.0, "rateStr": "37,990.00", "kind": "item" },
  { "section": "B", "bill": "B2.1.4", "desc": "Type D - depth above 2m and upto 2.5m", "unit": "No", "rate": 41550.0, "rateStr": "41,550.00", "kind": "item" },
  { "section": "B", "bill": "B2.1.5", "desc": "Type D - depth above 2.5m and upto 3.0m", "unit": "No", "rate": 58880.0, "rateStr": "58,880.00", "kind": "item" },
  
  { "section": "B", "bill": "B2.2", "desc": "Supply and placing of P.E inspection chamber, Internal Dia. 450mm", "unit": "Nil", "rate": null, "rateStr": "", "kind": "subsection" },
  { "section": "B", "bill": "B2.2.1", "desc": "Invert levels at depth less or equal to 0.75m", "unit": "No", "rate": 16330.0, "rateStr": "16,330.00", "kind": "item" },
  { "section": "B", "bill": "B2.3", "desc": "Supply and placing of P.E inspection chamber, Internal Dia. 600mm", "unit": "Nil", "rate": null, "rateStr": "", "kind": "subsection" },
  { "section": "B", "bill": "B2.3.1", "desc": "Invert levels at depth above 0.75 and to 1m", "unit": "No", "rate": 21590.0, "rateStr": "21,590.00", "kind": "item" },
  { "section": "B", "bill": "B2.3.2", "desc": "Invert levels at depth above 1m and to 1.5m", "unit": "No", "rate": 25640.0, "rateStr": "25,640.00", "kind": "item" },
  
  { "section": "B", "bill": "B3", "desc": "Construction of Traps and Air Vents", "unit": "Nil", "rate": null, "rateStr": "", "kind": "group" },
  { "section": "B", "bill": "B3.1", "desc": "Supply and install gully traps", "unit": "No", "rate": 3820.0, "rateStr": "3,820.00", "kind": "item" },
  { "section": "B", "bill": "B3.2", "desc": "Supply and install grease traps", "unit": "No", "rate": 3080.0, "rateStr": "3,080.00", "kind": "item" },
  { "section": "B", "bill": "B3.3", "desc": "Supply and install air vents", "unit": "Nil", "rate": null, "rateStr": "", "kind": "subsection" },
  { "section": "B", "bill": "B3.3.1", "desc": "Supply and install air vent 75mm dia., for one storey buildings", "unit": "No", "rate": 5190.0, "rateStr": "5,190.00", "kind": "item" },
  { "section": "B", "bill": "B3.3.2", "desc": "Supply and install air vent 75mm dia., for two or higher storey buildings", "unit": "No", "rate": 7160.0, "rateStr": "7,160.00", "kind": "item" },

  { "section": "B", "bill": "B4", "desc": "Extraovers", "unit": "Nil", "rate": null, "rateStr": "", "kind": "group" },
  { "section": "B", "bill": "B4.1", "desc": "Deeper trenches", "unit": "Nil", "rate": null, "rateStr": "", "kind": "subsection" },
  { "section": "B", "bill": "Note", "desc": "Extra over prices B1.1 for laying sewer pipes in deeper trenches", "unit": "Nil", "rate": null, "rateStr": "", "kind": "note" },
  { "section": "B", "bill": "B4.1.1", "desc": "At depth above 1.5m and upto 2m", "unit": "m", "rate": 2100.0, "rateStr": "2,100.00", "kind": "item" },
  { "section": "B", "bill": "B4.1.2", "desc": "At depth above 1.5m and upto 2.5m", "unit": "m", "rate": 6290.0, "rateStr": "6,290.00", "kind": "item" },
  { "section": "B", "bill": "B4.1.3", "desc": "At depth above 1.5m and upto 3m", "unit": "m", "rate": 12440.0, "rateStr": "12,440.00", "kind": "item" },
  
  { "section": "B", "bill": "B4.2", "desc": "Manhole covers", "unit": "Nil", "rate": null, "rateStr": "", "kind": "subsection" },
  { "section": "B", "bill": "B4.2.1", "desc": "Extra cost for provision, installation, sealing of medium duty D.I frame and cover on inspection chambers", "unit": "Nil", "rate": null, "rateStr": "", "kind": "subsection" },
  { "section": "B", "bill": "B4.2.1.1", "desc": "For Medium duty frame C covers, dim. up to 600x600", "unit": "No", "rate": 10580.0, "rateStr": "10,580.00", "kind": "item" },
  { "section": "B", "bill": "B4.2.2", "desc": "Extra Cost for provision, installation, sealing of heavy duty D.I frame and cover on inspection chambers", "unit": "Nil", "rate": null, "rateStr": "", "kind": "subsection" },
  { "section": "B", "bill": "B4.2.2.1", "desc": "For Heavy duty frame C covers, dim. up to 600x600", "unit": "No", "rate": 17330.0, "rateStr": "17,330.00", "kind": "item" },
  
  { "section": "B", "bill": "B4.3", "desc": "Reinforced blockwork", "unit": "Nil", "rate": null, "rateStr": "", "kind": "subsection" },
  { "section": "B", "bill": "B4.3.1", "desc": "Extraover prices B2.1 for provision of reinforced blockwork", "unit": "No", "rate": 7190.0, "rateStr": "7,190.00", "kind": "item" },
  
  { "section": "B", "bill": "B4.4", "desc": "Supply and installation of steps", "unit": "Nil", "rate": null, "rateStr": "", "kind": "subsection" },
  { "section": "B", "bill": "B4.4.1", "desc": "Extraover prices B2 for the supply, fixing, sealing and placing steps rubberised as specified, incl. the removal of old steps if any, and cutting, preparing holes for fixation of new steps, and epoxy mortar for sealing", "unit": "No", "rate": 620.0, "rateStr": "620.00", "kind": "item" },
  
  { "section": "B", "bill": "B4.5", "desc": "Connection on existing structures and sewers", "unit": "Nil", "rate": null, "rateStr": "", "kind": "subsection" },
  { "section": "B", "bill": "B4.5.1", "desc": "Connection to existing sewer DN 110/160 in private property/yard", "unit": "No", "rate": 19870.0, "rateStr": "19,870.00", "kind": "item" },
  { "section": "B", "bill": "B4.5.2", "desc": "Connection to existing manhole within private property/yard", "unit": "No", "rate": 23360.0, "rateStr": "23,360.00", "kind": "item" },

  // SECTION C
  { "section": "C", "bill": "SECTION C", "desc": "REINSTATEMENT", "unit": "Nil", "rate": null, "rateStr": "", "kind": "section" },
  { "section": "C", "bill": "C1", "desc": "Permanent surface reinstatement of trenches and manholes", "unit": "Nil", "rate": null, "rateStr": "", "kind": "group" },
  { "section": "C", "bill": "C1.1", "desc": "Reinstatement of Municipal councils asphalt concrete surfaced roads...", "unit": "m2", "rate": 3010.0, "rateStr": "3,010.00", "kind": "item" },
  { "section": "C", "bill": "C1.2", "desc": "Reinstatement of National classified asphalt concrete surfaced roads...", "unit": "m2", "rate": 3510.0, "rateStr": "3,510.00", "kind": "item" },
  
  { "section": "C", "bill": "C2", "desc": "Reinstatement of concrete access; works including the provision, laying and compacting of a base layer of crusher run 0/31.5, and concrete, laid and jointed as specified.", "unit": "Nil", "rate": null, "rateStr": "", "kind": "group" },
  { "section": "C", "bill": "C2.1", "desc": "In pavements/roads, access, parkings, with base layer 200mm thick, and 100mm thick concrete pavings", "unit": "m2", "rate": 1850.0, "rateStr": "1,850.00", "kind": "item" },
  { "section": "C", "bill": "C2.2", "desc": "Reinstatement in pavements with base layer 200mm thick and 100mm thick concrete pavings", "unit": "m2", "rate": 1850.0, "rateStr": "1,850.00", "kind": "item" },
  { "section": "C", "bill": "C2.3", "desc": "Reinstatement of gravel roads, access and pavements...", "unit": "m2", "rate": 4060.0, "rateStr": "4,060.00", "kind": "item" },
  { "section": "C", "bill": "C2.4", "desc": "Reinstatement of concrete slabs, access and pavements...", "unit": "m2", "rate": 2100.0, "rateStr": "2,100.00", "kind": "item" },
  { "section": "C", "bill": "C2.5", "desc": "Reinstatement of green area, to original state...", "unit": "m2", "rate": 260.0, "rateStr": "260.00", "kind": "item" },
  { "section": "C", "bill": "C2.6", "desc": "Reinstatement of internal/external tiles flooring...", "unit": "m2", "rate": 3330.0, "rateStr": "3,330.00", "kind": "item" },
  { "section": "C", "bill": "C2.7", "desc": "Reinstatement of bricks including the provision, laying and compacting of a base layer...", "unit": "m2", "rate": 3330.0, "rateStr": "3,330.00", "kind": "item" },
  { "section": "C", "bill": "C2.8", "desc": "Reinstatement of aggregate covered surface area, to original state...", "unit": "m2", "rate": 1490.0, "rateStr": "1,490.00", "kind": "item" },
  
  { "section": "C", "bill": "C3", "desc": "Milling of road surface", "unit": "Nil", "rate": null, "rateStr": "", "kind": "group" },
  { "section": "C", "bill": "C3.1", "desc": "Milling of road surface, 50 mm to 100 mm deep...", "unit": "m2", "rate": 460.0, "rateStr": "460.00", "kind": "item" },

  // SECTION D
  { "section": "D", "bill": "SECTION D", "desc": "DAYWORKS", "unit": "Nil", "rate": null, "rateStr": "", "kind": "section" },
  { "section": "D", "bill": "D1", "desc": "Plant", "unit": "Nil", "rate": null, "rateStr": "", "kind": "group" },
  { "section": "D", "bill": "D1.1", "desc": "110 h.p bulldozer", "unit": "Hr", "rate": 7140.0, "rateStr": "7,140.00", "kind": "item" },
  { "section": "D", "bill": "D1.2", "desc": "80 h.p bulldozer", "unit": "Hr", "rate": 5420.0, "rateStr": "5,420.00", "kind": "item" },
  { "section": "D", "bill": "D1.3", "desc": "115 h.p tracked excavator", "unit": "Hr", "rate": 3940.0, "rateStr": "3,940.00", "kind": "item" },
  { "section": "D", "bill": "D1.4", "desc": "70 h.p tracked excavator", "unit": "Hr", "rate": 2960.0, "rateStr": "2,960.00", "kind": "item" },
  { "section": "D", "bill": "D1.5", "desc": "70 h.p wheeled excavator/loader with backhoe", "unit": "Hr", "rate": 3940.0, "rateStr": "3,940.00", "kind": "item" },
  { "section": "D", "bill": "D1.6", "desc": "70 h.p Wheeled loader", "unit": "Hr", "rate": 3450.0, "rateStr": "3,450.00", "kind": "item" },
  { "section": "D", "bill": "D1.7", "desc": "10 tonne smooth wheeled roller", "unit": "Hr", "rate": 2470.0, "rateStr": "2,470.00", "kind": "item" },
  { "section": "D", "bill": "D1.8", "desc": "5 tonne vibrating roller", "unit": "Hr", "rate": 1360.0, "rateStr": "1,360.00", "kind": "item" },
  { "section": "D", "bill": "D1.9", "desc": "7 tonne tipping lorry", "unit": "Hr", "rate": 1850.0, "rateStr": "1,850.00", "kind": "item" },
  { "section": "D", "bill": "D1.10", "desc": "Lorry fitted with crane", "unit": "Hr", "rate": 2470.0, "rateStr": "2,470.00", "kind": "item" },
  { "section": "D", "bill": "D1.11", "desc": "8 tonne mobile crane", "unit": "Hr", "rate": 3940.0, "rateStr": "3,940.00", "kind": "item" },
  { "section": "D", "bill": "D1.12", "desc": "3000 litre water tanker with sprinkler", "unit": "Hr", "rate": 1000.0, "rateStr": "1,000.00", "kind": "item" },
  { "section": "D", "bill": "D1.13", "desc": "Low loader (mobilisation)", "unit": "Hr", "rate": 1000.0, "rateStr": "1,000.00", "kind": "item" },
  { "section": "D", "bill": "D1.14", "desc": "7/5 Concrete mixer", "unit": "Hr", "rate": 1000.0, "rateStr": "1,000.00", "kind": "item" },
  { "section": "D", "bill": "D1.15", "desc": "Poker type concrete vibrator complete with driving unit", "unit": "Hr", "rate": 260.0, "rateStr": "260.00", "kind": "item" },
  { "section": "D", "bill": "D1.16", "desc": "Pipe cutter complete with cutting disc & mobile generator", "unit": "Hr", "rate": 260.0, "rateStr": "260.00", "kind": "item" },
  { "section": "D", "bill": "D1.17", "desc": "50 mm delivery water pump and motor", "unit": "Hr", "rate": 510.0, "rateStr": "510.00", "kind": "item" },
  { "section": "D", "bill": "D1.18", "desc": "100 l/s compressor with all tools & hoses,complete", "unit": "Hr", "rate": 620.0, "rateStr": "620.00", "kind": "item" },
  { "section": "D", "bill": "D1.19", "desc": "250 l/s compressor with all tools & hoses,complete", "unit": "Hr", "rate": 620.0, "rateStr": "620.00", "kind": "item" },
  { "section": "D", "bill": "D1.20", "desc": "Hand operated frog hammer", "unit": "Hr", "rate": 260.0, "rateStr": "260.00", "kind": "item" },
  { "section": "D", "bill": "D1.21", "desc": "Bitumen sprayer", "unit": "Hr", "rate": 260.0, "rateStr": "260.00", "kind": "item" },
  { "section": "D", "bill": "D1.22", "desc": "1 m3 dumper", "unit": "Hr", "rate": 1000.0, "rateStr": "1,000.00", "kind": "item" },
  { "section": "D", "bill": "D1.23", "desc": "70 h.p agricultural tractor", "unit": "Hr", "rate": 1000.0, "rateStr": "1,000.00", "kind": "item" },
  { "section": "D", "bill": "D1.24", "desc": "1 tonne pick-up", "unit": "Hr", "rate": 510.0, "rateStr": "510.00", "kind": "item" },
  { "section": "D", "bill": "D1.25", "desc": "Jetting Unit", "unit": "Hr", "rate": 1360.0, "rateStr": "1,360.00", "kind": "item" },
  { "section": "D", "bill": "D1.26", "desc": "Wastewater Carrier", "unit": "Hr", "rate": 1360.0, "rateStr": "1,360.00", "kind": "item" },

  { "section": "D", "bill": "D2", "desc": "Labour", "unit": "Nil", "rate": null, "rateStr": "", "kind": "group" },
  { "section": "D", "bill": "D2.1", "desc": "Unskilled labourer", "unit": "Hr", "rate": 260.0, "rateStr": "260.00", "kind": "item" },
  { "section": "D", "bill": "D2.2", "desc": "Skilled labourer", "unit": "Hr", "rate": 260.0, "rateStr": "260.00", "kind": "item" },
  { "section": "D", "bill": "D2.3", "desc": "Night watchman", "unit": "Hr", "rate": 260.0, "rateStr": "260.00", "kind": "item" },
  { "section": "D", "bill": "D2.4", "desc": "Driver", "unit": "Hr", "rate": 380.0, "rateStr": "380.00", "kind": "item" },

  { "section": "D", "bill": "D3", "desc": "Materials", "unit": "Nil", "rate": null, "rateStr": "", "kind": "group" },
  { "section": "D", "bill": "D3.1", "desc": "Portland Cement in 50 Kg bags", "unit": "bag", "rate": 510.0, "rateStr": "510.00", "kind": "item" },
  { "section": "D", "bill": "D3.2", "desc": "Portland Cement in 25 Kg bags", "unit": "bag", "rate": 260.0, "rateStr": "260.00", "kind": "item" },
  { "section": "D", "bill": "D3.3", "desc": "Sand and fine aggregates", "unit": "m3", "rate": 2230.0, "rateStr": "2,230.00", "kind": "item" },
  { "section": "D", "bill": "D3.4", "desc": "Concrete aggregate 40, 20, 14 C10", "unit": "m3", "rate": 1360.0, "rateStr": "1,360.00", "kind": "item" },
  { "section": "D", "bill": "D3.5", "desc": "Macadam 1/2'", "unit": "m3", "rate": 1980.0, "rateStr": "1,980.00", "kind": "item" },
  { "section": "D", "bill": "D3.6", "desc": "Macadam 3/4'", "unit": "m3", "rate": 1980.0, "rateStr": "1,980.00", "kind": "item" },
  { "section": "D", "bill": "D3.7", "desc": "Formwork", "unit": "m2", "rate": 1980.0, "rateStr": "1,980.00", "kind": "item" },
  { "section": "D", "bill": "D3.8", "desc": "Crusher run material (40mm down)", "unit": "m3", "rate": 1730.0, "rateStr": "1,730.00", "kind": "item" },
  { "section": "D", "bill": "D3.9", "desc": "Mild steel reinforcement", "unit": "Kg", "rate": 130.0, "rateStr": "130.00", "kind": "item" },
  { "section": "D", "bill": "D3.10", "desc": "High yield reinforcement", "unit": "Kg", "rate": 130.0, "rateStr": "130.00", "kind": "item" },
  { "section": "D", "bill": "D3.11", "desc": "Horizontal timber shuttering class F2 finish", "unit": "m2", "rate": 1120.0, "rateStr": "1,120.00", "kind": "item" },
  { "section": "D", "bill": "D3.12", "desc": "Vertical timber shuttering class F2 finish", "unit": "m2", "rate": 1120.0, "rateStr": "1,120.00", "kind": "item" },
  { "section": "D", "bill": "D3.13", "desc": "Grouted stone pitching", "unit": "m2", "rate": 2100.0, "rateStr": "2,100.00", "kind": "item" },
  { "section": "D", "bill": "D3.14", "desc": "Penetration grade bitumen 60", "unit": "litre", "rate": 260.0, "rateStr": "260.00", "kind": "item" },
  { "section": "D", "bill": "D3.15", "desc": "Light duty manhole cover 20MPa, 450x600", "unit": "No", "rate": 4930.0, "rateStr": "4,930.00", "kind": "item" },
  { "section": "D", "bill": "D3.16", "desc": "Medium duty manhole cover 30MPa, 600x600", "unit": "No", "rate": 8000.0, "rateStr": "8,000.00", "kind": "item" },
  { "section": "D", "bill": "D3.17", "desc": "Heavy duty manhole cover 40MPa, 600x600", "unit": "No", "rate": 13530.0, "rateStr": "13,530.00", "kind": "item" },

  { "section": "D", "bill": "D3.18", "desc": "Pipes", "unit": "Nil", "rate": null, "rateStr": "", "kind": "subsection" },
  { "section": "D", "bill": "D3.18.1", "desc": "uPVC pipe DN 300", "unit": "m", "rate": 1850.0, "rateStr": "1,850.00", "kind": "item" },
  { "section": "D", "bill": "D3.18.2", "desc": "uPVC pipe DN 400", "unit": "m", "rate": 2230.0, "rateStr": "2,230.00", "kind": "item" },
  { "section": "D", "bill": "D3.18.3", "desc": "uPVC pipe DN 500", "unit": "m", "rate": 3940.0, "rateStr": "3,940.00", "kind": "item" },
  { "section": "D", "bill": "D3.18.4", "desc": "Concrete gravity pipe DN 400", "unit": "m", "rate": 13530.0, "rateStr": "13,530.00", "kind": "item" },
  { "section": "D", "bill": "D3.18.5", "desc": "Concrete gravity pipe DN 500", "unit": "m", "rate": 14760.0, "rateStr": "14,760.00", "kind": "item" },
  { "section": "D", "bill": "D3.18.6", "desc": "Concrete gravity pipe DN 600", "unit": "m", "rate": 15990.0, "rateStr": "15,990.00", "kind": "item" },
  { "section": "D", "bill": "D3.18.7", "desc": "D.I pipe DN 150", "unit": "m", "rate": 4930.0, "rateStr": "4,930.00", "kind": "item" },
  { "section": "D", "bill": "D3.18.8", "desc": "D.I pipe DN 200", "unit": "m", "rate": 6150.0, "rateStr": "6,150.00", "kind": "item" },
  { "section": "D", "bill": "D3.18.9", "desc": "D.I pipe DN 250", "unit": "m", "rate": 7380.0, "rateStr": "7,380.00", "kind": "item" },
  { "section": "D", "bill": "D3.18.10", "desc": "D.I pipe DN 300", "unit": "m", "rate": 8610.0, "rateStr": "8,610.00", "kind": "item" },
  { "section": "D", "bill": "D3.18.11", "desc": "D.I pipe DN 400", "unit": "m", "rate": 9840.0, "rateStr": "9,840.00", "kind": "item" },
  { "section": "D", "bill": "D3.18.12", "desc": "D.I pipe DN 500", "unit": "m", "rate": 11070.0, "rateStr": "11,070.00", "kind": "item" },
  { "section": "D", "bill": "D3.18.13", "desc": "D.I pipe DN 600", "unit": "m", "rate": 12290.0, "rateStr": "12,290.00", "kind": "item" },
  { "section": "D", "bill": "D3.18.14", "desc": "HDPE pipe DN 250", "unit": "m", "rate": 2230.0, "rateStr": "2,230.00", "kind": "item" },
  { "section": "D", "bill": "D3.18.15", "desc": "HDPE pipe DN 315", "unit": "m", "rate": 3450.0, "rateStr": "3,450.00", "kind": "item" },
  { "section": "D", "bill": "D3.18.16", "desc": "HDPE pipe DN 400", "unit": "m", "rate": 5550.0, "rateStr": "5,550.00", "kind": "item" },
  { "section": "D", "bill": "D3.18.17", "desc": "Clay pipe DN 150", "unit": "m", "rate": 750.0, "rateStr": "750.00", "kind": "item" },
  { "section": "D", "bill": "D3.18.18", "desc": "Clay pipe DN 200", "unit": "m", "rate": 1000.0, "rateStr": "1,000.00", "kind": "item" },

  { "section": "D", "bill": "D4", "desc": "All-in rates", "unit": "Nil", "rate": null, "rateStr": "", "kind": "group" },
  { "section": "D", "bill": "D4.1", "desc": "Concrete Grade C35/20/A as specified", "unit": "m3", "rate": 8250.0, "rateStr": "8,250.00", "kind": "item" },
  { "section": "D", "bill": "D4.2", "desc": "Concrete Grade C25/20/A as specified", "unit": "m3", "rate": 7760.0, "rateStr": "7,760.00", "kind": "item" },
  { "section": "D", "bill": "D4.3", "desc": "Concrete Grade C20/20/A as specified", "unit": "m3", "rate": 7380.0, "rateStr": "7,380.00", "kind": "item" },
  { "section": "D", "bill": "D4.4", "desc": "Concrete Grade C15/20/A as specified", "unit": "m3", "rate": 7380.0, "rateStr": "7,380.00", "kind": "item" },
  { "section": "D", "bill": "D4.5", "desc": "Disposal of silt from drains", "unit": "m3", "rate": 510.0, "rateStr": "510.00", "kind": "item" },
  { "section": "D", "bill": "D4.6", "desc": "Provide and compact 200 mm thick crusher run 0/31.5 incl watering and compacting as required", "unit": "m2", "rate": 4060.0, "rateStr": "4,060.00", "kind": "item" },
  { "section": "D", "bill": "D4.7", "desc": "Provide and lay Double seal surface dressing road reinstatement", "unit": "m2", "rate": 510.0, "rateStr": "510.00", "kind": "item" },
  { "section": "D", "bill": "D4.8", "desc": "Provide and lay Asphaltic concrete surface consisting of a prime coat and 40 mm thick wearing course", "unit": "m2", "rate": 1360.0, "rateStr": "1,360.00", "kind": "item" },
  { "section": "D", "bill": "D4.9", "desc": "Provide for excavation of unsuitable material in trench or area spots, backfilling with suitable material, disposal of excavated materials and compaction, all as specified", "unit": "m3", "rate": 2100.0, "rateStr": "2,100.00", "kind": "item" },
  { "section": "D", "bill": "D4.10", "desc": "Reinstatement of external tiles flooring including the provision, laying and compacting of a base layer 100mm thick of crusher run 0/31.5, a sand layer 50mm thick, concrete 100mm thick, and tiles grade A, thickness... laid and jointed as specified.", "unit": "m2", "rate": 3330.0, "rateStr": "3,330.00", "kind": "item" },
  { "section": "D", "bill": "D4.11", "desc": "Provide scaffolding 3m high including transport, mobilization, erection and demobilization.", "unit": "m", "rate": 40440.0, "rateStr": "40,440.00", "kind": "item" },
  { "section": "D", "bill": "D4.12", "desc": "Provide and compact bedding material incl. watering and compacting as required", "unit": "m3", "rate": 2340.0, "rateStr": "2,340.00", "kind": "item" },
  { "section": "D", "bill": "D4.13", "desc": "Construction of blockwork, including jointing and rendering on both sides as required.", "unit": "m2", "rate": 1120.0, "rateStr": "1,120.00", "kind": "item" },
  { "section": "D", "bill": "D4.14", "desc": "Excavation including carting away, trimming and compacting of base and sides as required", "unit": "m3", "rate": 260.0, "rateStr": "260.00", "kind": "item" },
  { "section": "D", "bill": "D4.15", "desc": "Supply, lay and compact crusher run including transport", "unit": "m3", "rate": 2470.0, "rateStr": "2,470.00", "kind": "item" },
  { "section": "D", "bill": "D4.16", "desc": "Provide and lay concrete flooring (Grade 25)", "unit": "m3", "rate": 9720.0, "rateStr": "9,720.00", "kind": "item" },

  { "section": "D", "bill": "D4.17", "desc": "Laying of pipes", "unit": "Nil", "rate": null, "rateStr": "", "kind": "subsection" },
  { "section": "D", "bill": "D4.17.1", "desc": "Gravity D.I pipe DN 200", "unit": "m", "rate": 2590.0, "rateStr": "2,590.00", "kind": "item" },
  { "section": "D", "bill": "D4.17.2", "desc": "Gravity D.I pipe DN 250", "unit": "m", "rate": 3940.0, "rateStr": "3,940.00", "kind": "item" },
  { "section": "D", "bill": "D4.17.3", "desc": "Gravity D.I pipe DN 300", "unit": "m", "rate": 3940.0, "rateStr": "3,940.00", "kind": "item" },
  { "section": "D", "bill": "D4.17.4", "desc": "Gravity D.I pipe DN 400", "unit": "m", "rate": 5170.0, "rateStr": "5,170.00", "kind": "item" },
  { "section": "D", "bill": "D4.17.5", "desc": "Gravity D.I pipe DN 500", "unit": "m", "rate": 5170.0, "rateStr": "5,170.00", "kind": "item" },
  { "section": "D", "bill": "D4.17.6", "desc": "Concrete gravity pipe DN 200", "unit": "m", "rate": 2590.0, "rateStr": "2,590.00", "kind": "item" },
  { "section": "D", "bill": "D4.17.7", "desc": "Concrete gravity pipe DN 300", "unit": "m", "rate": 3940.0, "rateStr": "3,940.00", "kind": "item" },
  { "section": "D", "bill": "D4.17.8", "desc": "Concrete gravity pipe DN 400", "unit": "m", "rate": 5170.0, "rateStr": "5,170.00", "kind": "item" },
  { "section": "D", "bill": "D4.17.9", "desc": "Concrete gravity pipe DN 500", "unit": "m", "rate": 5170.0, "rateStr": "5,170.00", "kind": "item" },
  { "section": "D", "bill": "D4.17.10", "desc": "HDPE pipe DN 250", "unit": "m", "rate": 3940.0, "rateStr": "3,940.00", "kind": "item" },
  { "section": "D", "bill": "D4.17.11", "desc": "HDPE pipe DN 315", "unit": "m", "rate": 3940.0, "rateStr": "3,940.00", "kind": "item" },
  { "section": "D", "bill": "D4.17.12", "desc": "HDPE pipe DN 400", "unit": "m", "rate": 5170.0, "rateStr": "5,170.00", "kind": "item" },
  { "section": "D", "bill": "D4.17.13", "desc": "HDPE pipe DN 500", "unit": "m", "rate": 5170.0, "rateStr": "5,170.00", "kind": "item" },

  { "section": "D", "bill": "D4.18", "desc": "Permanent reinstatement of boundary walls...", "unit": "Nil", "rate": null, "rateStr": "", "kind": "subsection" },
  { "section": "D", "bill": "D4.18.1", "desc": "Construction/Reconstruction of blockwalls 150mm thick incl RC foundation...", "unit": "m2", "rate": 1360.0, "rateStr": "1,360.00", "kind": "item" },
  { "section": "D", "bill": "D4.18.2", "desc": "Construction/Reconstruction of blockwalls 200mm thick incl RC foundation...", "unit": "m2", "rate": 1610.0, "rateStr": "1,610.00", "kind": "item" },
  { "section": "D", "bill": "D4.18.3", "desc": "Construction/Reconstruction of stone walls up to 400mm thick incl RC foundation...", "unit": "m2", "rate": 6400.0, "rateStr": "6,400.00", "kind": "item" },
  { "section": "D", "bill": "D4.18.4", "desc": "Construction/Reconstruction of stone walls more than 400mm thick incl RC foundation...", "unit": "m3", "rate": 6650.0, "rateStr": "6,650.00", "kind": "item" },
  
  { "section": "D", "bill": "D4.19", "desc": "Re-construction of poles...", "unit": "Nil", "rate": null, "rateStr": "", "kind": "subsection" },
  { "section": "D", "bill": "D4.19.1", "desc": "Reconstruction of concrete pole 150mm square maxi, Pole height 1m to 1.5m max", "unit": "No", "rate": 5780.0, "rateStr": "5,780.00", "kind": "item" },
  { "section": "D", "bill": "D4.19.2", "desc": "Reconstruction of concrete pole 200mm square, Pole height 1.5 to 2m", "unit": "No", "rate": 6270.0, "rateStr": "6,270.00", "kind": "item" },
  
  { "section": "D", "bill": "D4.20", "desc": "Reconstruction of concrete / blockwork drains incl RC foundation...", "unit": "Nil", "rate": null, "rateStr": "", "kind": "subsection" },
  { "section": "D", "bill": "D4.20.1", "desc": "Reconstruction of drain up to depth 0.2m", "unit": "No", "rate": 7380.0, "rateStr": "7,380.00", "kind": "item" },
  { "section": "D", "bill": "D4.20.2", "desc": "Reconstruction of drain up to depth 0.4m", "unit": "No", "rate": 12290.0, "rateStr": "12,290.00", "kind": "item" },
  { "section": "D", "bill": "D4.20.3", "desc": "Reconstruction of drain up to depth 0.6m", "unit": "No", "rate": 17460.0, "rateStr": "17,460.00", "kind": "item" },
  { "section": "D", "bill": "D4.20.4", "desc": "Reconstruction of drain up to depth 0.8m", "unit": "No", "rate": 20900.0, "rateStr": "20,900.00", "kind": "item" },
  { "section": "D", "bill": "D4.20.5", "desc": "Reconstruction of drain up to depth 1.0m", "unit": "No", "rate": 22130.0, "rateStr": "22,130.00", "kind": "item" },
  { "section": "D", "bill": "D4.20.6", "desc": "Reconstruction of drain up to depth 1.2 m and above", "unit": "No", "rate": 23360.0, "rateStr": "23,360.00", "kind": "item" },

  { "section": "D", "bill": "D4.21", "desc": "Supply, lay, join and test in trench PVC fittings in connection with house connections", "unit": "Nil", "rate": null, "rateStr": "", "kind": "subsection" },
  { "section": "D", "bill": "D4.21.1", "desc": "Y or T junction, 110/125 mm to ND 110/125mm", "unit": "No", "rate": 870.0, "rateStr": "870.00", "kind": "item" },
  { "section": "D", "bill": "D4.21.2", "desc": "Y or T junction, 110 or 125 mm to 160mm", "unit": "No", "rate": 1850.0, "rateStr": "1,850.00", "kind": "item" },
  { "section": "D", "bill": "D4.21.3", "desc": "Y or T junction, 160 to 160 mm", "unit": "No", "rate": 1850.0, "rateStr": "1,850.00", "kind": "item" },
  { "section": "D", "bill": "D4.21.4", "desc": "15 to 30 long radius bend, 110/125 mm", "unit": "No", "rate": 1000.0, "rateStr": "1,000.00", "kind": "item" },
  { "section": "D", "bill": "D4.21.5", "desc": "15 to 30 long radius bend, 160 mm", "unit": "No", "rate": 2830.0, "rateStr": "2,830.00", "kind": "item" },
  { "section": "D", "bill": "D4.21.6", "desc": "Antibackflow valve to DN 110 mm", "unit": "No", "rate": 25810.0, "rateStr": "25,810.00", "kind": "item" },
  { "section": "D", "bill": "D4.21.7", "desc": "Antibackflow pipe to DN 160 mm", "unit": "No", "rate": 34790.0, "rateStr": "34,790.00", "kind": "item" },
  { "section": "D", "bill": "D4.21.8", "desc": "Antibackflow valve to DN 200 mm", "unit": "No", "rate": 36870.0, "rateStr": "36,870.00", "kind": "item" },

  { "section": "D", "bill": "D4.22", "desc": "Traffic Management", "unit": "Nil", "rate": null, "rateStr": "", "kind": "subsection" },
  { "section": "D", "bill": "D4.22.1", "desc": "Police assistance (per policeman)", "unit": "Hr", "rate": 860.0, "rateStr": "860.00", "kind": "item" },
  { "section": "D", "bill": "D4.22.2", "desc": "Stop-go system operational during the day", "unit": "No", "rate": 5290.0, "rateStr": "5,290.00", "kind": "item" },
  { "section": "D", "bill": "D4.22.3", "desc": "Stop-go system operational during the night", "unit": "No", "rate": 7380.0, "rateStr": "7,380.00", "kind": "item" },
  { "section": "D", "bill": "D4.22.4", "desc": "Barricade (beyond working hours) for raising of manhole...", "unit": "No", "rate": 10210.0, "rateStr": "10,210.00", "kind": "item" },
  { "section": "D", "bill": "D4.22.5", "desc": "Traffic Diversion as approved by TMRSU", "unit": "No", "rate": 68340.0, "rateStr": "68,340.00", "kind": "item" },

  { "section": "D", "bill": "D4.23", "desc": "Crossings", "unit": "Nil", "rate": null, "rateStr": "", "kind": "group" },
  { "section": "D", "bill": "D4.23.1", "desc": "Crossing of drains, streams/culverts less than or equal to 1m...", "unit": "No", "rate": 14760.0, "rateStr": "14,760.00", "kind": "item" },
  { "section": "D", "bill": "D4.23.2", "desc": "Crossing of drains, streams/culverts more than 1m and less than 3m...", "unit": "No", "rate": 29510.0, "rateStr": "29,510.00", "kind": "item" },
  { "section": "D", "bill": "D4.23.3", "desc": "Crossing septic tanks or pits by house property sewers using D.I pipe sleeves...", "unit": "Nil", "rate": null, "rateStr": "", "kind": "subsection" },
  { "section": "D", "bill": "D4.23.3.1", "desc": "Crossing of concrete/blockwall septic or other underground tank, length not exceeding 3 m", "unit": "No", "rate": 12800.0, "rateStr": "12,800.00", "kind": "item" },
  { "section": "D", "bill": "D4.23.3.2", "desc": "Crossing of concrete/blockwall septic or other underground tank, length from 3m to 6m", "unit": "No", "rate": 25200.0, "rateStr": "25,200.00", "kind": "item" },
  { "section": "D", "bill": "D4.23.3.3", "desc": "Crossing of earth pits length not exceeding 3 m", "unit": "No", "rate": 11800.0, "rateStr": "11,800.00", "kind": "item" },
  { "section": "D", "bill": "D4.23.4", "desc": "Crossing of services of diameter/width greater or equal to 150 mm", "unit": "No", "rate": 16230.0, "rateStr": "16,230.00", "kind": "item" },

  { "section": "D", "bill": "D4.24.1", "desc": "Protection around sewers with concrete, as instructed by the Empoyer...", "unit": "m3", "rate": 8740.0, "rateStr": "8,740.00", "kind": "item" },
  
  { "section": "D", "bill": "D4.25", "desc": "Installation of Backdrop on internal or external backdrop in manhole", "unit": "Nil", "rate": null, "rateStr": "", "kind": "group" },
  { "section": "D", "bill": "D4.25.1", "desc": "For 160/200mm dia uPVC pipe", "unit": "Nil", "rate": null, "rateStr": "", "kind": "subsection" },
  { "section": "D", "bill": "D4.25.1.1", "desc": "internal backdrop up to 2m", "unit": "No", "rate": 18440.0, "rateStr": "18,440.00", "kind": "item" },
  { "section": "D", "bill": "D4.25.1.2", "desc": "internal backdrop from 2m to 3m", "unit": "No", "rate": 18440.0, "rateStr": "18,440.00", "kind": "item" },
  { "section": "D", "bill": "D4.25.1.3", "desc": "internal backdrop above 3m", "unit": "No", "rate": 30730.0, "rateStr": "30,730.00", "kind": "item" },
  { "section": "D", "bill": "D4.25.1.4", "desc": "external backdrop from 2m to 3m", "unit": "No", "rate": 31960.0, "rateStr": "31,960.00", "kind": "item" },
  { "section": "D", "bill": "D4.25.2", "desc": "For 250/300mm dia uPVC pipe", "unit": "Nil", "rate": null, "rateStr": "", "kind": "subsection" },
  { "section": "D", "bill": "D4.25.2.1", "desc": "internal backdrop up to 2m", "unit": "No", "rate": 20900.0, "rateStr": "20,900.00", "kind": "item" },
  { "section": "D", "bill": "D4.25.2.2", "desc": "internal backdrop from 2m to 3m", "unit": "No", "rate": 20900.0, "rateStr": "20,900.00", "kind": "item" },
  { "section": "D", "bill": "D4.25.2.3", "desc": "external backdrop up to 2m", "unit": "No", "rate": 33190.0, "rateStr": "33,190.00", "kind": "item" },
  { "section": "D", "bill": "D4.25.2.4", "desc": "external backdrop from 2m to 3m", "unit": "No", "rate": 34420.0, "rateStr": "34,420.00", "kind": "item" },

  { "section": "D", "bill": "D4.26", "desc": "Raising of existing manhole covers", "unit": "Nil", "rate": null, "rateStr": "", "kind": "group" },
  { "section": "D", "bill": "D4.26.1", "desc": "Raising of cover less or equal to 0.1m high", "unit": "No", "rate": 23360.0, "rateStr": "23,360.00", "kind": "item" },
  { "section": "D", "bill": "D4.26.2", "desc": "Raising of cover above 0.1m upto 0.2m high", "unit": "No", "rate": 24580.0, "rateStr": "24,580.00", "kind": "item" },
  { "section": "D", "bill": "D4.26.3", "desc": "Raising of cover above 0.1m upto 0.3m high", "unit": "No", "rate": 25810.0, "rateStr": "25,810.00", "kind": "item" },
  { "section": "D", "bill": "D4.26.4", "desc": "Raising of cover above 0.1m upto 0.5m high", "unit": "No", "rate": 27050.0, "rateStr": "27,050.00", "kind": "item" },
  { "section": "D", "bill": "D4.26.5", "desc": "Raising of cover above 0.1m upto 0.75m high", "unit": "No", "rate": 28280.0, "rateStr": "28,280.00", "kind": "item" },
  { "section": "D", "bill": "D4.26.6", "desc": "Raising of cover above 0.1m upto 1.0m high", "unit": "No", "rate": 29510.0, "rateStr": "29,510.00", "kind": "item" },

  { "section": "D", "bill": "D4.27", "desc": "Concrete thrust blocks in excavations...", "unit": "m3", "rate": 8520.0, "rateStr": "8,520.00", "kind": "item" },
  
  { "section": "D", "bill": "D4.28", "desc": "Backfilling of Pits", "unit": "Nil", "rate": null, "rateStr": "", "kind": "group" },
  { "section": "D", "bill": "D4.28.1", "desc": "Demolish and cart away cover slabs to existing soakage/absorption pits...", "unit": "No", "rate": 12290.0, "rateStr": "12,290.00", "kind": "item" },
  { "section": "D", "bill": "D4.28.2", "desc": "Allow for emptying and desludging of existing pits...", "unit": "No", "rate": 12290.0, "rateStr": "12,290.00", "kind": "item" },
  { "section": "D", "bill": "D4.28.3", "desc": "Trial pits up to 3m depth, incl. reinstatement", "unit": "No", "rate": 10460.0, "rateStr": "10,460.00", "kind": "item" },
  
  { "section": "D", "bill": "D4.29", "desc": "Rock Content", "unit": "Nil", "rate": null, "rateStr": "", "kind": "subsection" },
  { "section": "D", "bill": "D4.29.1", "desc": "Extra Over Items A1.1 and B1.1 for excavation whereby the rock content exceeds 80% by volume", "unit": "m", "rate": 8180.0, "rateStr": "8,180.00", "kind": "item" }
];
